name: 'Deploy to Schema Registry'
description: 'Deploy Avro schemas to Confluent Schema Registry'
inputs:
  schema-dir:
    description: 'Path to schema directory'
    required: true
    default: 'schemas'
  registry-url:
    description: 'Confluent Schema Registry URL'
    required: true
  api-key:
    description: 'Confluent API Key'
    required: true
  api-secret:
    description: 'Confluent API Secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate schemas
      shell: bash
      run: |
        SCHEMA_DIR="${{ inputs.schema-dir }}"
        echo "🔍 Validating schemas in $SCHEMA_DIR"
        find "$SCHEMA_DIR" -name '*.avsc' | while read schema_file; do
          if ! jq empty "$schema_file" &>/dev/null; then
            echo "❌ Invalid JSON in $schema_file"
            exit 1
          fi
        done
        echo "✅ All schemas validated"

    - name: Deploy & cleanup schemas
      shell: bash
      env:
        SCHEMA_REGISTRY_URL: ${{ inputs.registry-url }}
        API_KEY: ${{ inputs.api-key }}
        API_SECRET: ${{ inputs.api-secret }}
      run: |
        set -eo pipefail
        SCHEMA_DIR="${{ inputs.schema-dir }}"
        FAILED=0

        echo "🔐 Validating API key permissions..."
        if ! curl -sS -u "${API_KEY}:${API_SECRET}" \
          "${SCHEMA_REGISTRY_URL}/mode" >/dev/null; then
          echo "❌ FATAL: API key authentication failed or lacks basic permissions"
          exit 1
        fi

        echo "📂 Collecting local schemas..."
        LOCAL_SUBJECTS=$(find "$SCHEMA_DIR" -name '*.avsc' -exec basename {} .avsc \;)

        echo "📡 Fetching subjects from Schema Registry..."
        REMOTE_SUBJECTS=$(curl -sS -u "${API_KEY}:${API_SECRET}" \
          "${SCHEMA_REGISTRY_URL}/subjects" | jq -r '.[]')

        # --- Deploy or Update ---
        for schema_file in $(find "$SCHEMA_DIR" -name '*.avsc'); do
          subject_name=$(basename "$schema_file" .avsc)
          echo "🚀 Deploying schema: $subject_name"

          schema_content=$(jq -c . < "$schema_file")
          payload=$(jq -n --arg schema "$schema_content" \
            '{schema: $schema, schemaType: "AVRO"}')

          response=$(curl -sS -w "\n%{http_code}" \
            -u "${API_KEY}:${API_SECRET}" \
            -H "Content-Type: application/vnd.schemaregistry.v1+json" \
            -X POST \
            --data "$payload" \
            "${SCHEMA_REGISTRY_URL}/subjects/${subject_name}/versions" 2>&1) || true

          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n -1)

          case $http_code in
            200|201|202)
              echo "✅ Success! New version: $(echo "$response_body" | jq .id)"
              ;;
            409)
              echo "ℹ️ Schema already exists for subject: $subject_name"
              latest=$(curl -sS -u "${API_KEY}:${API_SECRET}" \
                "${SCHEMA_REGISTRY_URL}/subjects/${subject_name}/versions/latest" \
                | jq -c .schema)

              if [ "$latest" = "$schema_content" ]; then
                echo "✅ No changes. Schema is identical to latest version."
              else
                echo "🔄 Schema differs. Attempting update..."
                update_resp=$(curl -sS -w "\n%{http_code}" \
                  -u "${API_KEY}:${API_SECRET}" \
                  -H "Content-Type: application/vnd.schemaregistry.v1+json" \
                  -X POST \
                  --data "$payload" \
                  "${SCHEMA_REGISTRY_URL}/subjects/${subject_name}/versions" 2>&1) || true
                update_code=$(echo "$update_resp" | tail -n1)
                update_body=$(echo "$update_resp" | head -n -1)

                if [ "$update_code" -eq 200 ] || [ "$update_code" -eq 201 ]; then
                  echo "✅ Updated! New version: $(echo "$update_body" | jq .id)"
                else
                  if echo "$update_body" | grep -q "incompatible"; then
                    echo "❌ Compatibility check failed for subject: $subject_name"
                    echo "   👉 Fix schema to be backward compatible OR relax registry compatibility settings."
                  else
                    echo "❌ Failed to update schema: $update_body"
                  fi
                  FAILED=1
                fi
              fi
              ;;
            401|403)
              echo "❌ PERMISSION DENIED: $response_body"
              echo "   Required permission: 'Write' on subject: $subject_name"
              FAILED=1
              ;;
            422)
              echo "❌ Compatibility failed: $subject_name"
              echo "$response_body"
              FAILED=1
              ;;
            *)
              echo "❌ Unexpected error ($http_code): $response_body"
              FAILED=1
              ;;
          esac
        done

        # --- Cleanup (delete removed subjects) ---
        echo "🧹 Checking for subjects to delete..."
        for remote in $REMOTE_SUBJECTS; do
          if ! echo "$LOCAL_SUBJECTS" | grep -qw "$remote"; then
            echo "🗑️  Deleting subject not found locally: $remote"
            delete_resp=$(curl -sS -w "\n%{http_code}" \
              -u "${API_KEY}:${API_SECRET}" \
              -X DELETE \
              "${SCHEMA_REGISTRY_URL}/subjects/${remote}" 2>&1) || true
            delete_code=$(echo "$delete_resp" | tail -n1)
            delete_body=$(echo "$delete_resp" | head -n -1)
            if [ "$delete_code" -eq 200 ] || [ "$delete_code" -eq 204 ]; then
              echo "✅ Deleted subject: $remote"
            else
              echo "❌ Failed to delete subject $remote: $delete_body"
              FAILED=1
            fi
          fi
        done

        if [ $FAILED -ne 0 ]; then
          echo "::error::Some schemas failed to deploy or delete"
          exit 1
        fi
